### ISSUE TITLE
Add predicates for common use cases in PostStore and UserProfileStore

### ISSUE THREAD

**Issue by nathancoleman** [Suite436/Chatter#6]
It would probably be useful to have static predicate functions for common cases like retrieving latest posts, posts after a certain date, etc.

I found this [article](http://howtodoinjava.com/2014/04/04/how-to-use-predicate-in-java-8/) interesting regarding this approach. One example:

```
public static Predicate<Employee> isAgeMoreThan(Integer age) {
    return p -> p.getAge() > age;
}

public static List<Employee> filterEmployees (List<Employee> employees, Predicate<Employee> predicate) {
    return employees.stream().filter( predicate ).collect(Collectors.<Employee>toList());
}

// Usage
System.out.println(filterEmployees(employees, isAgeMoreThan(35)));
```

**Comment by sethau** [comment]
A couple comments on this proposal:

I don't think that any specific predicates should reside in either of the Proxy classes, as they should be very simple accessors for the hard storage. A better place for this logic would be either in a separate Predicate factory class, Proxy decorator (to wrap around the Proxy classes), or in the user classes such as FeedBuilder.

Second, I'm not completely convinced that we have a need yet to provide this level of abstraction. I firmly believe in not over-engineering a project until it's clear that there will be an ROI for doing so. I wold be in favor of fleshing out the other requirements (that would necessitate more Predicates) before trying to design our methods for abstracting out our standard Predicates into separate structures.

**Comment by sethau** [comment]
As per the pivot, this item is no longer needed. Closing.
