### ISSUE TITLE
Add support for comments on Posts

### ISSUE THREAD

**Issue by nathancoleman** [Suite436/Chatter#7]
Posts should support comments. This will most likely require a new CommentStore even though the comments would be tied to a post. Comment would need to have a back-reference to the post which, in our current architecture, means having a reference to the user who created the post and the post id.

**Comment by sethau** [comment]
Let's discuss this a bit more. The vision I had for was less of a "Facebook News Feed" and more of an "RSS/Twitter-esque Feed" that is automatically tailored to be relevant to each user. There's certainly value in having some sort of linkage between certain posts, but I don't know that I'd go the literal "comment" route. Thoughts?

**Comment by sethau** [comment]
As per the pivot, this item is no longer needed. Closing.
