### ISSUE TITLE
Allow delete and single-post-retrieval for PostStore

### ISSUE THREAD

**Issue by nathancoleman** [Suite436/Chatter#8]
This requires Post objects having an id that is either unique to that user or unique across every user. Unique for that user will require a user id when retrieving/deleting posts from the PostStore. This might be a better idea since it would prevent having to look through the entire PostStore HashMap for a post w/ only the id in hand.

**Comment by sethau** [comment]
I would agree that we should make post IDs unique on a per-user basis. The only time that a post's ID would be needed would be for deletes and for links (mentioned [here](https://github.com/Suite436/Chatter/issues/7)). Both of these use cases present easy opportunities for accessing the user ID as well as the post ID, so I think this is a prime example of fitting the architecture to the use case, thus benefiting everyone!

**Comment by sethau** [comment]
As per the pivot, this item is no longer needed. Closing.
